- hosts: localhost
  become: true
  tasks:
  - name: Install zsh
    apt: name=zsh
  - name: Change default shell to zsh
    shell: chsh -s `which zsh`
  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: Install zsh-syntax-highlighting plugin
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  - name: Update .zshrc
    shell: sed -i 's/(git/(git zsh-syntax-highlighting/' ~/.zshrc
